export const CLINIC_REPOSITORY = Symbol('CLINIC_REPOSITORY');
export const DOCTOR_REPOSITORY = Symbol('DOCTOR_REPOSITORY');
export const SPECIALTIE_REPOSITORY = Symbol('SPECIALTIE_REPOSITORY');
export const SCHEDULE_REPOSITORY = Symbol('SCHEDULE_REPOSITORY');
